### ISSUE TITLE
CNAME error

### ISSUE THREAD

**Issue by tvaught** [pydata/compilers-webpage#2]
When editing the index.md page on a fork using the github web interface editor, saving the changes results in an email from github:

The page build failed with the following error:

CNAME already taken: compilers.pydata.org

Looks like github trying to rebuild the docs manually perhaps?

**Comment by sdiehl** [comment]
I think the issue is that whenever Github sees a fork with a `gh-pages` branch it tries to attach it to the DNS record in `CNAME` which Github apparently forces to be unique in their system. Just my guess, seems like Github issue.

**Comment by tvaught** [comment]
On Feb 15, 2013, at 3:20 PM, Stephen Diehl notifications@github.com wrote:

> I think the issue is that whenever Github sees a fork with a gh-pages branch it tries to attach it to the DNS record in CNAME which Github apparently forces to be unique in their system. Just my guess, seems like Github issue.
> 
> —
> Reply to this email directly or view it on GitHub.

I think you're right.
