### ISSUE TITLE
what is "python-type-inference"?

### ISSUE THREAD

**Issue by gpshead** [pydata/compilers-webpage#3]
the page says "Python-type-inference is a Hindley-Milner type inference engine for Python with an OCaml implementation."

needs a website link.  i believe you mean https://code.google.com/p/python-type-inference/.

**Comment by sdiehl** [comment]
> what is python type inference?

Type inference or "type reconstruction" is a procedure for recovering the full type information from limited explicit type annotations.

The website link is there on the page, maybe the formatting was ambiguous I changed it a bit.

**Comment by gpshead** [comment]
i wasn't asking what type inferencing was, i was pointing out the lack of a link. ;)  thanks for the update with the website link!  bummer about the actual project being an undocumented likely unfinished student project.

**Comment by sdiehl** [comment]
Yeah, unfortunately most of the Python typing work is unfinished academic research. Alas...
